export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/main'
export const COMPARISON_ROUTE  = '/comparison'
export const HISTORY_ROUTE = '/history'
